# Storage agent configuration file

name: storage_agent
description: An agent to profile storage on the computer
tools_approval_required: true
skills_directory: /Users/mahadevgaonkar/code/google-adk-samples/skills
workspace_directory: /Users/mahadevgaonkar/code/google-adk-samples/storage_agent/workspace
skills:
  - storage
output_key: storage_agent_response
provider: vllm
model: Qwen/Qwen3-4B-Thinking-2507-FP8
endpoint:
  url: http://mahadev-ms7d28:8000/v1
  max_tokens: 4096
  temperature: 0.8
