# Wayz agent configuration file

name: wazy_agent
description: An agent to create a travel itinerary based on user preferences.
tools:
  - tavily_search
  - google_maps
tools_approval_required: false
skills_directory: /Users/mahadevgaonkar/code/google-adk-samples/skills
skills:
  - wazy
output_key: wazy_agent_response
provider: openai
model: gpt-4o
endpoint:
  url: http://mahadev-ms7d28:8000/v1
  max_tokens: 4096
  temperature: 0.8
