# Wayz agent configuration file

name: wazy_agent
description: An agent to create a travel itinerary based on user preferences.
tools:
  - tavily_search
  - google_maps
tools_approval_required: false
skills_directory: /app/skills
skills:
  - wazy
output_key: wazy_agent_response
provider: vllm
model: Qwen/Qwen3-4B-Thinking-2507-FP8
endpoint:
  url: http://10.0.0.147:8000/v1
  max_tokens: 4096
  temperature: 0.8
