# Wayz agent configuration file

name: wazy_agent
description: An agent to create a travel itinerary based on user preferences.
tools:
  - tavily_search
  - google_maps
tools_approval_required: false
skills_directory: /app/skills
skills:
  - wazy
output_key: wazy_agent_response
provider: openai
model: gpt-4.1
endpoint:
  url: http://10.0.0.147:8000/v1
  max_tokens: 4096
  temperature: 0.8
enable_truncation: True
context_window: 28288
